name: Deploy 

on: 
  push: 
    branches: 
      - master 
  pull_request:
    branches:  
      - master 


jobs:
  Build: 
    uses: ./.github/workflows/initial_build.yml 

  Server_Test: 
    uses: ./.github/workflows/server_test.yml 
    needs: Build


  deploy_dev: 
    strategy:
      matrix:
        env: [dev, prod, impl]
        dev: [9, 8, 7]
        exclude: 
          - env: dev  
            dev: 8 
          - env: dev 
            dev: 7 
    needs: Server_Test
    concurrency: ci-${{ github.ref }}
    if: ${{ github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'deploy_dev') }}
    # needs: [ lint, client_test, server_test, e2e_tests, anti_virus ]
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    env:
      APP_ENV: ${{ matrix.env }}
      dev: ${{ matrix.dev }}
    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: | 
          echo $APP_ENV
          echo $dev


