name: Initial building of images 



on: 
  workflow_call:
    secrets: 
      DOCKERHUB_USERNAME:
        required: true 
      DOCKERHUB_TOKEN:
        required: true 
      
    
    

jobs: 
  pre_deps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
  
  anti_virus:
    runs-on: ubuntu-latest
    container:
      image: clamav/clamav:0.104.0
    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.pull_request.head.sha }}
     


  build_db_migrate_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
  build_server_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      